CONFIGNAME=release
# On gcc, -fno-omit-frame-pointer implies -mno-omit-leaf-frame-pointer, but
# clang requires both to produce clean stack traces for Linux's "perf"
# See: https://bugs.llvm.org/show_bug.cgi?id=9825
CONFIGFLAGS=-DNDEBUG -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer

include Makefile.common
